[phases.setup]
nixPkgs = ["curl"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install -r requirements.txt",
    "mkdir -p /root/.u2net",
    "curl -L --retry 3 --retry-delay 5 -o /root/.u2net/u2net.onnx https://github.com/danielgatis/rembg/releases/download/v0.0.0/u2net.onnx"
]

[start]
cmd = "./start.sh" 